sport_category_color = {
    'bieganie' : 'rgb(31, 119, 180)',
    'sporty siłowe' : 'rgb(235, 74, 64)',
    'inne' : 'rgb(82, 188, 63)',
    'sporty piłkowe' : 'rgb(229, 134, 6)', 
    'zawody' : 'RED' ,
    '' : 'lightgray'
}

sport_color = {
    '': 'lightgray',
    'siłownia': 'rgb(235, 74, 64)',
    'bieganie': 'rgb(31, 119, 180)',
    'kalistenika': 'rgb(92, 83, 165)',
    'siatkówka': 'rgb(229, 134, 6)',
    'rower': 'rgb(82, 188, 63)',
    'Półmaraton Warszawski': 'RED',
    'piłka nożna': 'rgb(153, 201, 69)',
    'góry': 'rgb(165, 170, 153)',
    'plażówka': 'rgb(218, 165, 27)',
    'squash': 'rgb(204, 97, 176)',
    'ocr': 'rgb(36, 121, 108)',
    'Runmageddon Rekrut': 'RED',
    'Runmageddon Ultra': 'RED',
    'Bieg Powstania Warszawskiego': 'RED',
    'Bieg WOŚP': 'RED',
    'Półmaraton Praski': 'RED',
    'Maraton Warszawski': 'RED',
    'Sztafeta Ekiden': 'RED',
    'Bieg Niepodległości': 'RED',
    'Runmageddon Classic': 'RED',
    'Runmageddon Hardcore': 'RED',
    'pływanie' : 'rgb(47, 138, 196)',
    'Warszawska Dycha' : 'RED'
}

event_color = {
    '': 'lightgray',
    'siłownia': 'green',
    'bieganie': 'green',
    'kalistenika': 'green',
    'siatkówka': 'green',
    'rower': 'green',
    'Półmaraton Warszawski': 'RED',
    'piłka nożna': 'green',
    'góry': 'green',
    'plażówka': 'green',
    'squash': 'green',
    'ocr': 'green',
    'Runmageddon Rekrut': 'RED',
    'Runmageddon Ultra': 'RED',
    'Bieg Powstania Warszawskiego': 'RED',
    'Bieg WOŚP': 'RED',
    'Półmaraton Praski': 'RED',
    'Maraton Warszawski': 'RED',
    'Sztafeta Ekiden': 'RED',
    'Bieg Niepodległości': 'RED',
    'Runmageddon Classic': 'RED',
    'Runmageddon Hardcore': 'RED',
    'pływanie' : 'green',
    'Warszawska Dycha' : 'RED'
}

run_work = {
    '': 'lightgray',
    'siłownia': 'rgb(235, 74, 64)',
    'bieganie': 'rgb(31, 119, 180)',
    'kalistenika': 'rgb(92, 83, 165)',
    'siatkówka': 'lightgray',
    'rower': 'lightgray',
    'Półmaraton Warszawski': 'RED',
    'piłka nożna': 'lightgray',
    'góry': 'lightgray',
    'plażówka': 'lightgray',
    'squash': 'lightgray',
    'ocr': 'green',
    'Runmageddon Rekrut': 'RED',
    'Runmageddon Ultra': 'RED',
    'Bieg Powstania Warszawskiego': 'RED',
    'Bieg WOŚP': 'RED',
    'Półmaraton Praski': 'RED',
    'Maraton Warszawski': 'RED',
    'Sztafeta Ekiden': 'RED',
    'Bieg Niepodległości': 'RED',
    'Runmageddon Classic': 'RED',
    'Runmageddon Hardcore': 'RED',
    'pływanie' : 'lightgray',
    'Warszawska Dycha' : 'RED'
}
